import type { Asset, Project, Task } from "./domain";

export const tasks: Task[] = [
  {
    id: "TSK-0029",
    title: "Wohnbau Coburg – Steinweg 57 renovation status",
    asset: "Steinweg 57",
    status: "Waiting",
    priority: "High",
    owner: "Max Meisner",
    waitingFor: "Okossy / Yoram",
    waitingDays: 7,
    deadline: "31 Jul",
    nextStep: "Await response from Wohnbau",
    description: "Waiting for construction timetable and response from the project team.",
    flag: "overdue",
    updates: ["Today · Follow-up remains outstanding.", "31 Jul · Requested status update from Okossy / Yoram."],
  },
  {
    id: "TSK-0018",
    title: "Chase overdue survey packages – Hahnmühle & Square",
    asset: "Hotels",
    status: "Waiting",
    priority: "High",
    owner: "Max Meisner",
    waitingFor: "Okossy",
    waitingDays: 14,
    nextStep: "Await responses from the architects",
    description: "Building files, archive review, legal documents, 3D survey, photos and room book are being tracked.",
    flag: "waiting",
    updates: ["31 Jul · Follow-up emails sent to architects and project contacts."],
  },
  {
    id: "TSK-0024",
    title: "Krystof – sign contract",
    asset: "613 Group",
    status: "Waiting",
    priority: "High",
    owner: "Max Meisner",
    waitingFor: "Tax Office",
    waitingDays: 38,
    nextStep: "Finalise and submit signed contract",
    description: "Employment contract remains under external review.",
    flag: "attention",
    updates: [],
  },
  {
    id: "TSK-0025",
    title: "Business license 613 Investment Group GmbH",
    asset: "613 Group",
    status: "Waiting",
    priority: "High",
    owner: "Max Meisner",
    waitingFor: "IHK",
    waitingDays: 44,
    nextStep: "Confirm IHK registration",
    description: "Business license submitted to the Chamber of Commerce.",
    flag: "attention",
    updates: [],
  },
  {
    id: "TSK-0008",
    title: "Order confirmation 2475 for quote 2730",
    asset: "Allee 7",
    status: "In progress",
    priority: "High",
    owner: "Max Meisner",
    deadline: "22 Sep",
    nextStep: "Sign / return order confirmation",
    description: "Parkett goods ordered and appointment booked.",
    updates: [],
  },
  {
    id: "TSK-0075",
    title: "Goldbergstraße lock change",
    asset: "613 Group",
    status: "Open",
    priority: "High",
    owner: "Max Meisner",
    deadline: "11 Aug",
    nextStep: "Wait for Michael",
    description: "Change the locks and coordinate execution.",
    updates: [],
  },
  {
    id: "TSK-0017",
    title: "Acceptance documents / elevators 396346 + 396347",
    asset: "Allee 7",
    status: "In progress",
    priority: "High",
    owner: "Max Meisner",
    nextStep: "Submit remaining documents",
    description: "Track remaining acceptance documents for both elevators.",
    updates: [],
  },
  {
    id: "TSK-0037",
    title: "Claim number S0064560090-613",
    asset: "Allee 7",
    status: "In progress",
    priority: "Medium",
    owner: "Max Meisner",
    nextStep: "Track claim settlement with insurer",
    description: "Water damage claim and associated documentation.",
    updates: [],
  },
];

export const assets: Asset[] = [
  { id: "A001", name: "Allee 7", type: "Apartment building", status: "Active", city: "Coburg", units: 16, openTasks: 11, projects: 2 },
  { id: "A004", name: "Hotel 57", type: "Hotel", status: "Under examination", city: "Coburg", units: 17, openTasks: 3, projects: 1 },
  { id: "A005", name: "Hahnmühle", type: "Hotel", status: "Active", city: "Coburg", units: 19, openTasks: 6, projects: 1 },
  { id: "A010", name: "Square", type: "Hotel", status: "Active", city: "Coburg", units: 14, openTasks: 6, projects: 1 },
  { id: "A003", name: "Office Building", type: "Mixed object", status: "Active", city: "Coburg", units: 8, openTasks: 9, projects: 0 },
  { id: "A008", name: "Adam Riese", type: "Hotel", status: "Under examination", city: "Bad Staffelstein", units: 25, openTasks: 2, projects: 1 },
  { id: "A012", name: "Old Post", type: "Hotel", status: "Under examination", city: "Pfarrweisach", units: 53, openTasks: 1, projects: 1 },
];

export const projects: Project[] = [
  { id: "PRJ-0001", asset: "Hotel 57", phase: "01 Bestand & Untersuchungen", progress: 14, health: "At risk", completion: "Apr 2028", nextMilestone: "3D survey & room book" },
  { id: "PRJ-0002", asset: "Hahnmühle", phase: "02 Konzept & Vorabstimmung", progress: 22, health: "On track", completion: "TBD", nextMilestone: "Heritage assessment" },
  { id: "PRJ-0003", asset: "Square", phase: "02 Konzept & Vorabstimmung", progress: 31, health: "At risk", completion: "TBD", nextMilestone: "Authority coordination" },
  { id: "PRJ-0004", asset: "Adam Riese", phase: "01 Bestand & Untersuchungen", progress: 11, health: "Delayed", completion: "TBD", nextMilestone: "Legal / survey package" },
  { id: "PRJ-0005", asset: "Old Post", phase: "01 Bestand & Untersuchungen", progress: 9, health: "On track", completion: "TBD", nextMilestone: "Archive package" },
];
