const tasks=[
{id:"TSK-0029",title:"Wohnbau Coburg – Steinweg 57 renovation status",asset:"Steinweg 57",status:"Waiting",priority:"High",owner:"Max Meisner",waitingFor:"Okossy / Yoram",days:7,deadline:"31 Jul",next:"Await response from Wohnbau",flag:"overdue",desc:"Waiting for construction timetable and response from the project team.",updates:["Today · Follow-up remains outstanding.","31 Jul · Requested status update from Okossy / Yoram."]},
{id:"TSK-0018",title:"Chase overdue survey packages – Hahnmühle & Square",asset:"Hotels",status:"Waiting",priority:"High",owner:"Max Meisner",waitingFor:"Okossy",days:14,deadline:"—",next:"Await responses from the architects",flag:"waiting",desc:"Building files, archive review, legal documents, 3D survey, photos and room book are being tracked.",updates:["31 Jul · Follow-up emails sent to architects and project contacts."]},
{id:"TSK-0024",title:"Krystof – sign contract",asset:"613 Group",status:"Waiting",priority:"High",owner:"Max Meisner",waitingFor:"Tax Office",days:38,deadline:"—",next:"Finalise and submit signed contract",flag:"attention",desc:"Employment contract remains under external review.",updates:[]},
{id:"TSK-0025",title:"Business license 613 Investment Group GmbH",asset:"613 Group",status:"Waiting",priority:"High",owner:"Max Meisner",waitingFor:"IHK",days:44,deadline:"—",next:"Confirm IHK registration",flag:"attention",desc:"Business license submitted to the Chamber of Commerce.",updates:[]},
{id:"TSK-0008",title:"Order confirmation 2475 for quote 2730",asset:"Allee 7",status:"In progress",priority:"High",owner:"Max Meisner",deadline:"22 Sep",next:"Sign / return order confirmation",desc:"Parkett goods ordered and appointment booked.",updates:[]},
{id:"TSK-0075",title:"Goldbergstraße lock change",asset:"613 Group",status:"Open",priority:"High",owner:"Max Meisner",deadline:"11 Aug",next:"Wait for Michael",desc:"Change the locks and coordinate execution.",updates:[]},
{id:"TSK-0017",title:"Acceptance documents / elevators 396346 + 396347",asset:"Allee 7",status:"In progress",priority:"High",owner:"Max Meisner",deadline:"—",next:"Submit remaining documents",desc:"Track remaining acceptance documents for both elevators.",updates:[]}
];
const projects=[
{id:"PRJ-0001",asset:"Hotel 57",phase:"01 Bestand & Untersuchungen",progress:14,health:"At risk",completion:"Apr 2028",next:"3D survey & room book"},
{id:"PRJ-0002",asset:"Hahnmühle",phase:"02 Konzept & Vorabstimmung",progress:22,health:"On track",completion:"TBD",next:"Heritage assessment"},
{id:"PRJ-0003",asset:"Square",phase:"02 Konzept & Vorabstimmung",progress:31,health:"At risk",completion:"TBD",next:"Authority coordination"},
{id:"PRJ-0004",asset:"Adam Riese",phase:"01 Bestand & Untersuchungen",progress:11,health:"Delayed",completion:"TBD",next:"Legal / survey package"},
{id:"PRJ-0005",asset:"Old Post",phase:"01 Bestand & Untersuchungen",progress:9,health:"On track",completion:"TBD",next:"Archive package"}
];
const assets=[
{id:"A001",name:"Allee 7",type:"Apartment building",status:"Active",city:"Coburg",units:16,tasks:11,projects:2},
{id:"A004",name:"Hotel 57",type:"Hotel",status:"Under examination",city:"Coburg",units:17,tasks:3,projects:1},
{id:"A005",name:"Hahnmühle",type:"Hotel",status:"Active",city:"Coburg",units:19,tasks:6,projects:1},
{id:"A010",name:"Square",type:"Hotel",status:"Active",city:"Coburg",units:14,tasks:6,projects:1},
{id:"A003",name:"Office Building",type:"Mixed object",status:"Active",city:"Coburg",units:8,tasks:9,projects:0},
{id:"A008",name:"Adam Riese",type:"Hotel",status:"Under examination",city:"Bad Staffelstein",units:25,tasks:2,projects:1}
];
const c=document.getElementById("content"),nav=document.getElementById("nav"),drawer=document.getElementById("drawer"),backdrop=document.getElementById("backdrop");let filter="All";
const head=(e,t,d)=>`<header class="pageHead"><div class="eyebrow">${e}</div><h1>${t}</h1><p>${d}</p></header>`;
const pill=s=>`<span class="pill status-${s.toLowerCase().replaceAll(" ","-")}">${s}</span>`;
const hpill=s=>`<span class="pill health-${s.toLowerCase().replaceAll(" ","-")}">${s}</span>`;
const metric=(l,v,m,t="")=>`<div class="metric ${t}"><span>${l}</span><strong>${v}</strong><small>${m}</small></div>`;
function home(){return `<div class="stack">${head("Friday · Operations overview","Good afternoon, Max.","Here is what needs attention across the portfolio.")}<section class="metrics">${metric("Open tasks","43","Across all owners")}${metric("Overdue","3","Needs action","danger")}${metric("Waiting external","10","External dependencies","warn")}${metric("Active projects","5","3 need attention")}</section><div class="grid2"><section class="panel"><div class="sectionTitle"><h2>Attention required</h2><button>View all →</button></div>${tasks.filter(t=>t.flag).slice(0,4).map(t=>`<div class="attentionRow clickable" onclick="openTask('${t.id}')"><i class="flag ${t.flag}"></i><div class="main"><strong>${t.title}</strong><small>${t.asset} · ${t.id}</small></div>${pill(t.status)}<div class="age">${t.days}d waiting</div></div>`).join("")}</section><section class="panel"><div class="sectionTitle"><h2>Portfolio pulse</h2></div><div class="pulse"><div><span>Assets tracked</span><strong>19</strong></div><div><span>Active assets</span><strong>9</strong></div><div><span>Development projects</span><strong>5</strong></div><div><span>Hotels in pilot</span><strong>4</strong></div></div></section></div><section class="panel"><div class="sectionTitle"><h2>Development portfolio</h2><button onclick="setView('projects')">Open projects →</button></div>${projects.map(p=>`<div class="projectRow"><div><strong>${p.asset}</strong><small>${p.phase}</small></div><div><small>${p.progress}% · ${p.completion}</small><div class="bar"><i style="width:${p.progress}%"></i></div></div>${hpill(p.health)}<div><small>Next milestone</small><strong>${p.next}</strong></div></div>`).join("")}</section></div>`}
function myWork(){const od=tasks.filter(t=>t.flag==="overdue"),w=tasks.filter(t=>t.status==="Waiting"),up=tasks.filter(t=>t.status!=="Waiting"&&t.flag!=="overdue");const sec=(title,a)=>`<section class="panel"><div class="sectionTitle"><h2>${title} · ${a.length}</h2></div>${a.map(t=>`<div class="workRow clickable" onclick="openTask('${t.id}')"><button class="circle"></button><div class="main"><strong>${t.title}</strong><small>${t.asset} · ${t.id}</small></div><span class="priority ${t.priority.toLowerCase()}">${t.priority}</span>${pill(t.status)}<div class="next"><small>Next step</small><strong>${t.next}</strong></div><div class="${t.flag==="overdue"?"danger":""}">${t.days?`${t.days}d`:t.deadline}</div></div>`).join("")}</section>`;return `<div class="stack">${head("Personal workspace","My Work","A focused view of what you need to move next.")}<div class="workSummary"><div><span>Assigned</span><strong>${tasks.length}</strong></div><div><span>Overdue</span><strong class="danger">${od.length}</strong></div><div><span>Waiting</span><strong>${w.length}</strong></div><div><span>Upcoming</span><strong>${up.length}</strong></div></div>${sec("Overdue",od)}${sec("Waiting",w)}${sec("This week",up)}</div>`}
function taskView(){const v=filter==="All"?tasks:tasks.filter(t=>t.status===filter);return `<div class="stack">${head("Operations","Tasks","One task record, multiple views. This preview is isolated and uses mock data only.")}<section class="panel authPanel"><div><span class="eyebrow">Google Workspace connection</span><strong>OAuth client not configured in static preview</strong><small>Live task source remains locked; production Sheets are not being written to.</small></div><span class="authHint">Runtime-only feature</span></section><div class="toolbar"><div class="tabs">${["All","Open","In progress","Waiting","Done"].map(f=>`<button class="${filter===f?"active":""}" onclick="filterTasks('${f}')">${f}</button>`).join("")}</div><button class="filter">☷ Filters</button></div><div class="tableWrap"><table class="table"><thead><tr><th>Task</th><th>Property</th><th>Status</th><th>Priority</th><th>Owner</th><th>Deadline</th><th>Next step</th></tr></thead><tbody>${v.map(t=>`<tr onclick="openTask('${t.id}')"><td><span class="id">${t.id}</span><strong>${t.title}</strong>${t.days?`<small>Waiting ${t.days} days</small>`:""}</td><td>${t.asset}</td><td>${pill(t.status)}</td><td><span class="priority ${t.priority.toLowerCase()}">${t.priority}</span></td><td><span class="person"><span class="mini">MM</span>${t.owner}</span></td><td class="${t.flag==="overdue"?"danger":""}">${t.deadline}</td><td>${t.next}</td></tr>`).join("")}</tbody></table></div></div>`}
function assetView(){return `<div class="stack">${head("Portfolio","Assets","Operational asset index. Financial source data stays in the existing Asset Overview.")}<div class="assets">${assets.map(a=>`<article class="assetCard"><div class="assetHead"><span class="assetId">${a.id}</span><span class="assetStatus ${a.status==="Under examination"?"exam":""}">${a.status}</span></div><h2>${a.name}</h2><p>${a.type} · ${a.city}</p><div class="stats"><div><span>Units / rooms</span><strong>${a.units}</strong></div><div><span>Open tasks</span><strong>${a.tasks}</strong></div><div><span>Projects</span><strong>${a.projects}</strong></div></div><button class="openAsset">Open asset →</button></article>`).join("")}</div></div>`}
function projectView(){return `<div class="stack">${head("Development","Projects","Portfolio view before the Hotel 57 Gantt pilot is connected.")}<div class="tableWrap"><table class="table"><thead><tr><th>Project</th><th>Phase</th><th>Progress</th><th>Health</th><th>Owner</th><th>Completion</th><th>Next milestone</th></tr></thead><tbody>${projects.map(p=>`<tr><td><span class="id">${p.id}</span><strong>${p.asset} Development</strong></td><td>${p.phase}</td><td>${p.progress}%<div class="bar"><i style="width:${p.progress}%"></i></div></td><td>${hpill(p.health)}</td><td><span class="person"><span class="mini">MM</span>Max Meisner</span></td><td>${p.completion}</td><td>${p.next}</td></tr>`).join("")}</tbody></table></div></div>`}
function setView(v){document.querySelectorAll("[data-view]").forEach(b=>b.classList.toggle("active",b.dataset.view===v));c.innerHTML=({home,"my-work":myWork,tasks:taskView,assets:assetView,projects:projectView}[v]||home)()}
function openTask(id){const t=tasks.find(x=>x.id===id);if(!t)return;drawer.innerHTML=`<div class="drawerHead"><div><span class="id">${t.id}</span><h2>${t.title}</h2></div><button class="close" onclick="closeDrawer()">×</button></div><div class="drawerStatus">${pill(t.status)}<span class="priority ${t.priority.toLowerCase()}">${t.priority}</span></div><div class="details"><div class="detail"><span>Property</span><strong>${t.asset}</strong></div><div class="detail"><span>Owner</span><strong>${t.owner}</strong></div><div class="detail"><span>Deadline</span><strong>${t.deadline}</strong></div><div class="detail"><span>Waiting for</span><strong>${t.waitingFor||"—"}</strong></div></div><section class="drawerSection"><span>Next step</span><p>${t.next}</p></section><section class="drawerSection"><span>Description / progress</span><p>${t.desc}</p></section><section class="drawerSection"><span>Activity</span>${t.updates.length?t.updates.map(u=>`<p class="activity">${u}</p>`).join(""):`<p class="muted">No updates yet.</p>`}</section>`;drawer.classList.remove("hidden");backdrop.classList.remove("hidden")}
function closeDrawer(){drawer.classList.add("hidden");backdrop.classList.add("hidden")}
function filterTasks(f){filter=f;setView("tasks")}
nav.addEventListener("click",e=>{const b=e.target.closest("[data-view]");if(b)setView(b.dataset.view)});backdrop.addEventListener("click",closeDrawer);window.setView=setView;window.openTask=openTask;window.closeDrawer=closeDrawer;window.filterTasks=filterTasks;setView("home");
